# Generated by Django 3.0 on 2019-12-18 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Customer', '0004_customer_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_project', models.CharField(max_length=50, verbose_name='Nombre del Proyecto')),
                ('need', models.TextField(verbose_name='Necesidad')),
                ('slug', models.SlugField(verbose_name='Slug')),
                ('comments', models.TextField(verbose_name='Comentarios')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('bussines', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.Customer', verbose_name='Empresa')),
            ],
        ),
    ]
