# Generated by Django 3.0 on 2019-12-18 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0002_auto_20191218_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='folio',
            field=models.IntegerField(unique=True, verbose_name='Folio'),
        ),
    ]
