# Generated by Django 3.0 on 2020-01-03 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0005_auto_20200103_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='justification',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='limitations',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='requirements',
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limitations', models.TextField(verbose_name='Limitaciones')),
                ('requirements', models.TextField(verbose_name='Requerimientos ')),
                ('justification', models.TextField(verbose_name='Justificación')),
                ('price', models.FloatField(verbose_name='Precio Total')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Projects.Projects', verbose_name='Proyecto')),
            ],
        ),
    ]
