# Generated by Django 3.0 on 2020-01-03 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0006_auto_20200103_1535'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proposal',
            options={'verbose_name': 'Propuesta', 'verbose_name_plural': 'Propuestas'},
        ),
        migrations.AddField(
            model_name='proposal',
            name='status',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Finalizada', 'Finalizada'), ('Con Cambios', 'Com cambios')], default=1, max_length=50, verbose_name='Status'),
            preserve_default=False,
        ),
    ]
