# Generated by Django 3.0 on 2019-12-17 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='representative',
            field=models.CharField(max_length=50, verbose_name='Representante'),
        ),
    ]
