# Generated by Django 3.0 on 2019-12-26 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0004_customer_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='slug',
            field=models.SlugField(default='abc', verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
